<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\About\About.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>About.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Categories\Categories.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Categories.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Common\Common.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Common.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\History\History.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>History.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Main\Main.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Main.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ProductDetails\ProductDetails.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductDetails.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ProductTable\ProductTable.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductTable.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\About\About.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>About.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Categories\Categories.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Categories.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Common\Common.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Common.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\History\History.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>History.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Main\Main.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Main.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProductDetails\ProductDetails.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductDetails.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProductTable\ProductTable.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductTable.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
