//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaywrightBull.Resources.ProductTable {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductTable() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaywrightBull.Resources.ProductTable.ProductTable", typeof(ProductTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     ▄▄     ▄▄▄▄      ▄▄▄▄                                                    ▄▄                                         
        ///   ████    ▀▀██      ▀▀██                                                    ██                        ██               
        ///   ████      ██        ██                ██▄███▄    ██▄████   ▄████▄    ▄███▄██  ██    ██   ▄█████▄  ███████   ▄▄█████▄ 
        ///  ██  ██     ██        ██                ██▀  ▀██   ██▀      ██▀  ▀██  ██▀  ▀██  ██    ██  ██▀    ▀    ██      ██▄▄▄▄ ▀ 
        ///  ██████     ██        █ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     ▄▄▄▄                                          
        ///  ██▀▀▀▀█                                         
        /// ██▀        ▄█████▄  ▄▄█████▄   ▄████▄   ▄▄█████▄ 
        /// ██         ▀ ▄▄▄██  ██▄▄▄▄ ▀  ██▄▄▄▄██  ██▄▄▄▄ ▀ 
        /// ██▄       ▄██▀▀▀██   ▀▀▀▀██▄  ██▀▀▀▀▀▀   ▀▀▀▀██▄ 
        ///  ██▄▄▄▄█  ██▄▄▄███  █▄▄▄▄▄██  ▀██▄▄▄▄█  █▄▄▄▄▄██ 
        ///    ▀▀▀▀    ▀▀▀▀ ▀▀   ▀▀▀▀▀▀     ▀▀▀▀▀    ▀▀▀▀▀▀ .
        /// </summary>
        internal static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receiving products.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    ▄▄▄▄              ▄▄                           
        ///  ██▀▀██     ██      ██                           
        /// ██    ██  ███████   ██▄████▄   ▄████▄    ██▄████ 
        /// ██    ██    ██      ██▀   ██  ██▄▄▄▄██   ██▀     
        /// ██    ██    ██      ██    ██  ██▀▀▀▀▀▀   ██      
        ///  ██▄▄██     ██▄▄▄   ██    ██  ▀██▄▄▄▄█   ██      
        ///   ▀▀▀▀       ▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀▀    ▀▀.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ▄▄▄▄▄▄                                           
        /// ██▀▀▀▀██                                         
        /// ██    ██   ▄█████▄  ██▄████▄   ▄███▄██  ▄▄█████▄ 
        /// ███████    ▀ ▄▄▄██  ██▀   ██  ██▀  ▀██  ██▄▄▄▄ ▀ 
        /// ██  ▀██▄  ▄██▀▀▀██  ██    ██  ██    ██   ▀▀▀▀██▄ 
        /// ██    ██  ██▄▄▄███  ██    ██  ▀██▄▄███  █▄▄▄▄▄██ 
        /// ▀▀    ▀▀▀  ▀▀▀▀ ▀▀  ▀▀    ▀▀   ▄▀▀▀ ██   ▀▀▀▀▀▀  
        ///                                ▀████.
        /// </summary>
        internal static string Rangs {
            get {
                return ResourceManager.GetString("Rangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Related products.
        /// </summary>
        internal static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select (↓↑) and press &quot;Enter&quot; to submit or any other key to go back..
        /// </summary>
        internal static string SelectOrBack {
            get {
                return ResourceManager.GetString("SelectOrBack", resourceCulture);
            }
        }
    }
}
